### ISSUE TITLE
Gerber files

### ISSUE THREAD

**Issue by rkurbatov** [scrapcomputing/486SocketBlaster#4]
Hi! Thank you for your work, I definitely want to give it a try.

I have some soldering experience but not a PCB development so never used KiCAD. Could you please provide Gerber files as it's the simplest way to order these boards somewhere like PCBWay or JLC PCB? Thanks in advance.

And what is the thickness of the board? I probably missed that in the video.

**Comment by scrapcomputing** [comment]
Hi, 
The gerber files can be found in the release section: https://github.com/scrapcomputing/486SocketBlaster/releases
I should probably add a link to them in the readme text.

Regarding the PCB thickness, it shouldn't matter too much. My PCBs are 1.6mm thick and I think you can go a little bit thicker or thinner and there should be no issue at all.
