### ISSUE TITLE
Need to buy it.

### ISSUE THREAD

**Issue by dirsors** [scrapcomputing/486SocketBlaster#6]
Hi. I'm from Brazil and I would like if you can build one of these and sell it for me. I would buy it from you. Thank you!

**Comment by scrapcomputing** [comment]
Hi, 
Sorry but I can't sell them. I am not a professional, so it takes me a very long time to make these boards, and the result is not of the best quality. 
You can order the boards from the PCB manufacturer of your choice by just uploading the zipped gerber files (found in the release section), and you can easily find the rest of the components online. If you don't have the soldering skills or equipment you may ask your local cellphone/electronics repair shop to solder one for you.
Thanks!
