### ISSUE TITLE
Gerber RS 274x format

### ISSUE THREAD

**Issue by dirsors** [scrapcomputing/486SocketBlaster#7]
I would like to ask something very important so that the company I hired can build the boards: The project available in Gerber RS-274X Format. Thank you so much!

**Comment by scrapcomputing** [comment]
Hi, I am not 100% sure, but I think the gerber files should be compatible with the RS-274X format. Most board manufacturers should be fine with the gerber files in the releases. 
Have they already rejected the gerber files? And if so, could you please share the reason why they rejected them?

**Comment by dirsors** [comment]
They didn't tell me why, they simply said it needs to be in Gerber RS-274X format. Can you export in this format? I would appreciate it.

**Comment by scrapcomputing** [comment]
There is not much information about this online and from what I can tell kicad is already generating RS-274X. But perhaps your fab does not like the X2 extensions? I generated the gereber files without these X2 extensions. Could you try these out (see attached)
[486SocketBlaster_rev0.5_gerbers_noX2.zip](https://github.com/scrapcomputing/486SocketBlaster/files/13232421/486SocketBlaster_rev0.5_gerbers_noX2.zip)
?

**Comment by dirsors** [comment]
Thank you. Tomorrow is holiday here in Brazil and the fab will open only on friday, 03. I'll give a return as soon as possible.

**Comment by wrljet** [comment]
Novice comment here.  What FAB wouldn't accept/handle all formats?

**Comment by dirsors** [comment]
Look what the fab said:
"Kicad não abrimos, vc precisa enviar os arquivos em Gerber no formato RS 274x"
"We don't open Kicad, you need to send the files in Gerber in the format RS 274x"
The company is https://www.micropress.com.br/

**Comment by scrapcomputing** [comment]
Ah so if I understand correctly you probably sent them the source files (kicad) instead of the gerber files. The gerber files are listed in the releases and are include "_gerbers_" in the filename, like: https://github.com/scrapcomputing/486SocketBlaster/releases/download/rev0.5/486SocketBlaster_rev0.5_gerbers.zip

**Comment by dirsors** [comment]
Oh, you're right. I didn't check the "Release" section, but only the kicad folder at master branch. I think they'll accept it.

**Comment by scrapcomputing** [comment]
Yeah, I think they should work fine. Glad we figured out what the issue was.
